name: Cryptic Backend Docs Build
on:
  push:
    branches:
      - master
      - experimental

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Prepare Push with Github
        run: |
          git config --local user.email "cryptic-game@protonmail.com"
          git config --local user.name "Cryptic Bot"
          git remote add github "https://cryptic-bot:${{ secrets.GH_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git checkout gh-pages
          rm ./javadoc/latest/* -rf
          touch ./javadoc/latest/.gitkeep
          git add ./javadoc/latest/
          git commit -m "Remove old docs"
          git checkout ${GITHUB_REF##*/}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build Docs with Gradle
        run: ./gradlew aggregateJavadoc createDocs
      - name: Push Docs with Github
        run: |
          git show gh-pages:javadoc/latest javadoc/latest
          git checkout gh-pages
          git add ./javadoc/latest/
          git commit -m "Update docs"
          git push github gh-pages

