name: Cryptic Backend Docs Build
on:
  push:
    branches:
      - master
      - experimental

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.13
        uses: actions/setup-java@v1
        with:
          java-version: 1.13
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build Docs with Gradle
        run: ./gradlew aggregateJavadocs
      - name: Include Custom CSS into Docs with Gradle
        run: ./gradlew createDocs
      - name: Push Docs with Github
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git remote add github "https://JannikEmmerich:${{ secrets.GH_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git add ./docs/
          git commit -m "Update Docs"
          git push github HEAD:${GITHUB_REF}

